runqemu : removed all noisy echos and also used runqemu-gen-tap script to destroy and create tap interafaces during pxe boot . signed off by: Pradeep Gaddam<Pradeep.r.Gaddam@intel.com>

diff --git a/scripts/runqemu b/scripts/runqemu
--- a/scripts/runqemu
+++ b/scripts/runqemu
@@ -59,12 +59,9 @@ error() {
 }
 
 MACHINE=${MACHINE:=""}
-echo $MACHINE
 KERNEL=${KERNEL:=""}
-echo $KERNEL
 ROOTFS=${ROOTFS:=""}
 PXEROOTFS=${ROOTFS:=""}
-echo $ROOTFS
 VM=${VM:=""}
 FSTYPE=""
 LAZY_ROOTFS=""
@@ -72,7 +69,7 @@ SCRIPT_QEMU_OPT=""
 SCRIPT_QEMU_EXTRA_OPT=""
 SCRIPT_KERNEL_OPT=""
 SERIALSTDIO=""
-
+OECORE_NATIVE_SYSROOT=""
 # Determine whether the file is a kernel or QEMU image, and set the
 # appropriate variables
 process_filename() {
@@ -91,7 +88,6 @@ process_filename() {
 		if [ -z "$FSTYPE" -o "$FSTYPE" = "$EXT" ]; then
 		    FSTYPE=$EXT
 		    ROOTFS=$filename
-		    echo $ROOTFS	
 		else
 		    error "conflicting FSTYPE types [$FSTYPE] and [$EXT]"
 		fi
@@ -125,7 +121,6 @@ while true; do
             [ -z "$ROOTFS" ] || \
 		error "conflicting ROOTFS args [$ROOTFS] and [$arg]"
             if [ -f "$arg" ]; then
-		echo "Process filw=e Name"
                 process_filename $arg
             elif [ -d "$arg" ]; then
                 # Handle the case where the nfsroot dir has -image-
@@ -134,17 +129,15 @@ while true; do
                 FSTYPE=nfs
                 ROOTFS=$arg
             else
-		echo "lazy rootfs" 
                 ROOTFS=$arg
                 LAZY_ROOTFS="true"
             fi
             ;;
         "ramfs")
-	    echo "ramfs"	
             FSTYPE=cpio.gz
             RAMFS=true
             ;;
-	"pxe")
+	     "pxe")
             PXE=true
             ;;
         "iso")
@@ -219,7 +212,6 @@ while true; do
     esac
     shift
 done
-
 
 if [ ! -c /dev/net/tun ] ; then
 	echo "TUN control device /dev/net/tun is unavailable; you may need to enable TUN (e.g. sudo modprobe tun)"
@@ -431,48 +423,29 @@ findimage() {
     exit 1
 }
 
-
-
-pxe_setup_tap() {
+pxe_setup_tap_test() {
    SCRIPT_DIR=`dirname $0`
-   RUNQEMU_IFUP="$SCRIPT_DIR/runqemu-ifup"
-   if [ ! -x "$RUNQEMU_IFUP" ]; then
-        echo "Error: Unable to find the runqemu-ifup script in $SCRIPT_DIR"
+   RUNQEMU_GEN_TAP="$SCRIPT_DIR/runqemu-gen-tapdevs"
+   if [ ! -x "$RUNQEMU_GEN_TAP" ]; then
+        echo "Error: Unable to find the runqemu-gen-tapdevs script in $SCRIPT_DIR"
         exit 1
    fi
-
-   IFCONFIG=`which ip 2> /dev/null`
-   if [ -z "$IFCONFIG" ]; then
-        # Is it ever anywhere else?
-        IFCONFIG=/sbin/ip
-   fi
-   if [ ! -x "$IFCONFIG" ]; then
-       echo "$IFCONFIG cannot be executed"
-       exit 1
-   fi
-
-   TUNCTL=/usr/sbin/tunctl
-   if [[ ! -x "$TUNCTL" || -d "$TUNCTL" ]]; then
-        echo "Error: $TUNCTL is not an executable"
-        usage
-   fi
-   # Ensure we start with a clean slate
-   for tap in `$IFCONFIG link | grep tap | awk '{ print \$2 }' | sed s/://`; do
-        echo "Note: Destroying pre-existing tap interface $tap..."
-        $TUNCTL -d $tap
-   done
-
 
    b=$(pwd)
    TUID=$(id -u)
    GID=$(id -g)
-   ifup=`sudo $RUNQEMU_IFUP $TUID $GID / 2>&1`
+   NUM=0
+   ifup=`sudo $RUNQEMU_GEN_TAP $TUID $GID $NUM $OECORE_NATIVE_SYSROOT 2>&1`
    if [ $? -ne 0 ]; then
        echo "Error running tunctl: $ifup"
        exit 1
    fi
-
-
+   NUM=1 
+   ifup=`sudo $RUNQEMU_GEN_TAP $TUID $GID $NUM $OECORE_NATIVE_SYSROOT 2>&1`
+   if [ $? -ne 0 ]; then
+       echo "Error running tunctl: $ifup"
+       exit 1
+   fi
 }
 
 pxe_start_dnsmasq() {
@@ -514,7 +487,6 @@ pxe_boot() {
 
         OECORE_NATIVE_SYSROOT=$OE_TMPDIR/sysroots/$BUILD_SYS
    fi
-   
    mkdir -p $DEPLOY_DIR_IMAGE/EFI
    mkdir -p $DEPLOY_DIR_IMAGE/EFI/BOOT
    printf "menuentry \"linux\" {
@@ -522,7 +494,7 @@ linux /%s
 initrd /%s
 }" $kernel_file $PXEROOTFS > $DEPLOY_DIR_IMAGE/EFI/BOOT/grub.cfg
 
-   pxe_setup_tap
+   pxe_setup_tap_test
    pxe_start_dnsmasq
    QEMU="$OECORE_NATIVE_SYSROOT/usr/bin/qemu-system-x86_64"
    QEMUNETWORKCMD="-boot n -netdev tap,id=vmnet0,ifname=tap0,script=no,downscript=no -device rtl8139,netdev=vmnet0"
@@ -570,7 +542,6 @@ fi
 # core-image-sato
 if [ "$LAZY_ROOTFS" = "true" ]; then
     setup_path_vars 1
-    echo "Assuming $ROOTFS really means $DEPLOY_DIR_IMAGE/$ROOTFS-$MACHINE.$FSTYPE"
     PXEROOTFS=$ROOTFS-$MACHINE.$FSTYPE
     ROOTFS=$DEPLOY_DIR_IMAGE/$ROOTFS-$MACHINE.$FSTYPE
 fi
@@ -588,7 +559,6 @@ fi
 # ROOTFS is now set for all cases
 
 if [ "$PXE" = true ] ; then
-   echo "Pxe is enabled" ;
    pxe_boot
    exit 1
 fi
