runqemu-ifup : Changed this script to make sure we search for the executable tunctl not just in rootfilesystem/usr/sbin but also in rootfilesystem/usr/bin , also fixed a bug in executing a ifconfig command. signed off by : Pradeep Gaddam<Pradeep.r.Gaddam@intel.com

diff --git a/scripts/runqemu-ifup b/scripts/runqemu-ifup
--- a/scripts/runqemu-ifup
+++ b/scripts/runqemu-ifup
@@ -53,8 +53,11 @@ NATIVE_SYSROOT_DIR=$3
 
 TUNCTL=$NATIVE_SYSROOT_DIR/usr/sbin/tunctl
 if [ ! -x "$TUNCTL" ]; then
-       echo "Error: Unable to find tunctl binary in '$NATIVE_SYSROOT_DIR/usr/sbin', please bitbake qemu-helper-native"
-	exit 1
+       TUNCTL=$NATIVE_SYSROOT_DIR/usr/bin/tunctl
+       if [ ! -x "$TUNCTL" ]; then
+       		echo "Error: Unable to find tunctl binary in '$NATIVE_SYSROOT_DIR/usr/sbin' and '$NATIVE_SYSROOT_DIR/usr/bin', please bitbake qemu-helper-native"
+        	exit 1
+       fi
 fi
 
 TAP=`$TUNCTL -b $GROUP 2>&1`
